stages:
  - test
  - build
  - deploy

include:
  - 'prototyping/pipeline.yml'

build-images:
  stage: build
  image: docker:19.03
  tags:
    - docker-priv
  services:
    - docker:19.03-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - echo "$CONTAINER_KEY" | docker login -u "$GITLAB_ACCESS_USER" registry.socs.uoguelph.ca --password-stdin
    - docker build -t registry.socs.uoguelph.ca/hnantais/f22_cis3760_team106online/web web/
    - docker build -t registry.socs.uoguelph.ca/hnantais/f22_cis3760_team106online/server server/
    - docker push registry.socs.uoguelph.ca
  # rules:
  # - if: '$CI_COMMIT_REF_PROTECTED == "true"'

deploy-images:
  stage: deploy
  script:
    - curl -i https://$AdvisorLink:kqk5nPXutJsibLHJTej75wcjyJovbxkwyLvLY7aznccvz8sKBHanPXZYNpwd@advisorlink.scm.azurewebsites.net/api/registry/webhook
  # rules:
  # - if: '$CI_COMMIT_REF_PROTECTED == "true"'
