version: '3.8'
services:
  web:
    image: registry.socs.uoguelph.ca/hnantais/f22_cis3760_team106online/web
    restart: always
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - server

  server:
    image: registry.socs.uoguelph.ca/hnantais/f22_cis3760_team106online/server
    restart: always
    networks:
      - my-network

networks:
  my-network:
