version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - server

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
