test-html-parser:
  stage: test
  image: python:3.10
  when: manual
  before_script:
    - cd prototyping
    - python --version && pip install .
  script:
    - python3 -m unittest src/tests/test_parser.py -v

test-search-cli:
  stage: test
  image: python:3.10
  when: manual
  before_script:
    - cd prototyping
    - python --version && pip install .
  script:
    - python3 -m unittest src/tests/test_search.py -v
